#!/usr/bin/env python3
"""
FILE: tests/test_blunt_report.py
PURPOSE: Tests for engine.render.blunt_report
         - all 6 section headers present
         - word count within limits
         - no motive language
         - fail-closed on bad input
         - JSON output shape
         - support count uses adjudication

Run with: python -m pytest tests/test_blunt_report.py -v
"""

import pytest

from engine.render.blunt_report import (
    render_blunt_report,
    render_blunt_report_json,
    _trim_bullets,
    _enforce_word_limit,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _minimal_enriched() -> dict:
    """Build a minimal enriched substrate for renderer testing."""
    return {
        "article": {"title": "Test Article"},
        "adjudicated_whole_article_judgment": {
            "classification": "reporting",
            "confidence": "high",
        },
        "adjudicated_claims": [
            {
                "group_id": "G1",
                "text": "The economy grew by 3% last quarter according to official data",
                "centrality": 3,
                "adjudication": "kept",
                "tally": {"supported_votes": 2, "unsupported_votes": 0},
            },
            {
                "group_id": "G2",
                "text": "Government policy was described as effective by officials",
                "centrality": 2,
                "adjudication": "kept",
                "tally": {"supported_votes": 2, "unsupported_votes": 0},
            },
            {
                "group_id": "G3",
                "text": "Critics say the numbers are misleading",
                "centrality": 2,
                "adjudication": "rejected",
                "tally": {"supported_votes": 0, "unsupported_votes": 2},
            },
        ],
        "phase2": {
            "openai": {
                "whole_article_judgment": {"classification": "reporting", "confidence": "high"},
            },
            "gemini": {
                "whole_article_judgment": {"classification": "analysis", "confidence": "medium"},
            },
        },
        "reads_like": {
            "label": "reporting with minor structural concerns",
            "flags": {"has_reporting_structure": True},
            "matched_rule": 6,
        },
        "load_bearing": {
            "load_bearing_group_ids": ["G1"],
            "load_bearing_texts": ["The economy grew by 3%"],
            "weak_link_group_ids": [],
            "weak_link_texts": [],
            "argument_fragility": "low",
            "source": "centrality_only",
        },
        "ranked_omissions": [
            {"merged_text": "No independent economic data cited", "severity": "important"},
            {"merged_text": "Opposing analyst views not included", "severity": "minor"},
        ],
        "priority_signals": [
            {"rank": 1, "signal_type": "high_centrality_rejected", "score": 0.85,
             "summary": "A high-centrality claim was rejected by reviewers", "source_id": "G3"},
        ],
        "causal_detections": [],
        "baseline_detections": [],
        "official_detections": [],
        "story_clusters": [],
        "evidence_bank": {"items": []},
        "evidence_lookup": {},
        "structural_forensics": {},
        "argument_integrity": None,
    }


# ---------------------------------------------------------------------------
# Section header tests
# ---------------------------------------------------------------------------

class TestSectionHeaders:

    def test_all_six_headers_present(self):
        md = render_blunt_report(_minimal_enriched())
        assert "## What the object appears to be" in md
        assert "## What the object reads like" in md
        assert "## The story in brief" in md
        assert "## How the story is put together" in md
        assert "## What's missing" in md
        assert "## Bottom line" in md

    def test_report_title(self):
        md = render_blunt_report(_minimal_enriched())
        assert "# The Blunt Report" in md

    def test_article_title_in_header(self):
        md = render_blunt_report(_minimal_enriched())
        assert "Test Article" in md

    def test_footer_present(self):
        md = render_blunt_report(_minimal_enriched())
        assert "Generated by Survivor" in md


# ---------------------------------------------------------------------------
# Content tests
# ---------------------------------------------------------------------------

class TestContent:

    def test_classification_appears(self):
        md = render_blunt_report(_minimal_enriched())
        assert "reporting" in md.lower()

    def test_reads_like_label_appears(self):
        md = render_blunt_report(_minimal_enriched())
        assert "reporting with minor structural concerns" in md

    def test_kept_claims_shown(self):
        md = render_blunt_report(_minimal_enriched())
        assert "economy grew" in md

    def test_rejected_claims_not_in_story_brief(self):
        """Section 3 should only show kept claims."""
        md = render_blunt_report(_minimal_enriched())
        # The story in brief section should not contain the rejected claim
        story_start = md.index("## The story in brief")
        story_end = md.index("## How the story is put together")
        story_section = md[story_start:story_end]
        assert "Critics say" not in story_section

    def test_reviewer_split_shown(self):
        md = render_blunt_report(_minimal_enriched())
        assert "Reviewers split" in md

    def test_no_reviewer_split_when_unanimous(self):
        enriched = _minimal_enriched()
        enriched["phase2"]["gemini"]["whole_article_judgment"]["classification"] = "reporting"
        md = render_blunt_report(enriched)
        assert "Reviewers split" not in md

    def test_fragility_in_output(self):
        md = render_blunt_report(_minimal_enriched())
        # "low" fragility should produce "structurally stable"
        assert "structurally stable" in md

    def test_omissions_shown(self):
        md = render_blunt_report(_minimal_enriched())
        assert "independent economic data" in md

    def test_minor_omissions_not_in_blunt(self):
        md = render_blunt_report(_minimal_enriched())
        missing_start = md.index("## What's missing")
        missing_end = md.index("## Bottom line")
        missing_section = md[missing_start:missing_end]
        assert "Opposing analyst" not in missing_section

    def test_support_count_uses_adjudication(self):
        md = render_blunt_report(_minimal_enriched())
        # 2 kept out of 3 total
        assert "2 of 3 core claims supported" in md


# ---------------------------------------------------------------------------
# Word count tests
# ---------------------------------------------------------------------------

class TestWordCount:

    def test_default_under_400_words(self):
        md = render_blunt_report(_minimal_enriched())
        words = len(md.split())
        assert words <= 400

    def test_trim_bullets_basic(self):
        section = "## Header\n\nIntro:\n\n- Bullet 1\n- Bullet 2\n- Bullet 3\n- Bullet 4\n"
        trimmed = _trim_bullets(section, 2)
        assert trimmed.count("- ") == 2

    def test_trim_bullets_noop_when_under(self):
        section = "## Header\n\n- Bullet 1\n- Bullet 2\n"
        trimmed = _trim_bullets(section, 5)
        assert trimmed == section

    def test_enforce_word_limit_noop_under(self):
        sections = ["Short section.\n"] * 6
        result = _enforce_word_limit(sections, max_words=300)
        assert result == sections


# ---------------------------------------------------------------------------
# Fail-closed tests
# ---------------------------------------------------------------------------

class TestFailClosed:

    def test_empty_enriched(self):
        md = render_blunt_report({})
        assert "## What the object appears to be" in md
        assert "not assessed" in md.lower()

    def test_none_reads_like(self):
        enriched = _minimal_enriched()
        enriched["reads_like"] = {"error": "module failed"}
        md = render_blunt_report(enriched)
        assert "## What the object reads like" in md
        assert "Not assessed." in md

    def test_error_load_bearing(self):
        enriched = _minimal_enriched()
        enriched["load_bearing"] = {"error": "module failed"}
        md = render_blunt_report(enriched)
        assert "## How the story is put together" in md
        assert "Not assessed." in md

    def test_error_omissions(self):
        enriched = _minimal_enriched()
        enriched["ranked_omissions"] = {"error": "module failed"}
        md = render_blunt_report(enriched)
        assert "## What's missing" in md
        assert "Not assessed." in md


# ---------------------------------------------------------------------------
# No motive language tests
# ---------------------------------------------------------------------------

class TestNoMotiveLanguage:

    def test_no_intentionally(self):
        md = render_blunt_report(_minimal_enriched())
        assert "intentionally" not in md.lower()

    def test_no_deliberately(self):
        md = render_blunt_report(_minimal_enriched())
        assert "deliberately" not in md.lower()

    def test_no_trying_to(self):
        md = render_blunt_report(_minimal_enriched())
        assert "trying to" not in md.lower()

    def test_no_designed_to(self):
        md = render_blunt_report(_minimal_enriched())
        assert "designed to" not in md.lower()


# ---------------------------------------------------------------------------
# JSON output tests
# ---------------------------------------------------------------------------

class TestJsonOutput:

    def test_json_keys(self):
        obj = render_blunt_report_json(_minimal_enriched())
        expected_keys = {
            "what_it_appears_to_be", "what_it_reads_like", "story_in_brief",
            "how_put_together", "whats_missing", "bottom_line",
        }
        assert set(obj.keys()) == expected_keys

    def test_json_classification(self):
        obj = render_blunt_report_json(_minimal_enriched())
        assert obj["what_it_appears_to_be"]["classification"] == "reporting"

    def test_json_support_count(self):
        obj = render_blunt_report_json(_minimal_enriched())
        assert obj["bottom_line"]["supported_count"] == 2
        assert obj["bottom_line"]["total_count"] == 3

    def test_json_claims_are_kept_only(self):
        obj = render_blunt_report_json(_minimal_enriched())
        claims = obj["story_in_brief"]["claims"]
        for c in claims:
            assert c["adjudication"] == "kept"

    def test_json_empty_enriched(self):
        obj = render_blunt_report_json({})
        assert isinstance(obj, dict)
        assert obj["bottom_line"]["total_count"] == 0
